#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#server:
#  port: 8888

spring:
  application:
    name: post-service
  config:
    import: optional:configserver:http://localhost:8086

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/post-service
#    username: postgres
#    password: yasso
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#application:
#  config:
#    student-url: http://localhost:8090/v1/user