eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: http://localhost:8089
          predicates:
            - Path=/auth/**
        - id: partage
          uri: http://localhost:8088
          predicates:
            - Path=/partage/**
        - id: group
          uri: http://localhost:4044
          predicates:
            - Path=/group/**
        - id: group-user
          uri: http://localhost:4441
          predicates:
            - Path=/group-user/**
        - id: ami
          uri: http://localhost:8090
          predicates:
            - Path=/ami/**
        - id: notification
          uri: http://localhost:8091
          predicates:
            - Path=/notification/**
        - id: commentaire
          uri: http://localhost:8091
          predicates:
            - Path=/commentaires/**
        - id: interaction
          uri: http://localhost:8091
          predicates:
            - Path=/interactions/**
management:
  tracing:
    sampling:
      probability: 1.0

