eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 4440

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/group
    username: mariam
    password: 0572ml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    data:
      jpa:
        repositories:
          enabled: true