spring:
  application:
    name: IDENTITY-SERVICE
  config:
    import: optional:configserver:http://localhost:8086
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 8089
